name: 'GitHub Notify Deployment Action'

description: 'GitHub Notify Deployment Action'

inputs:
  environment:
    description: 'Environment to deploy'
    required: true
    default: 'sandbox'
  revision:
    description: 'Revision to deploy'
    required: true
  deploy-state:
    description: 'State of deployment'
    required: true
    default: 'successful'
  jira:
    description: 'Notify Jira'
    required: false
    default: 'false'
  jira-ticket:
    description: 'Any string to catch the tickets from'
    required: false
  new-relic:
    description: 'Notify New Relic'
    required: false
    default: 'false'
  new-relic-application-id:
    description: 'New Relic Application ID to ad the marker'
    required: false
    default: 'false'
  slack:
    description: 'Notify Slack'
    required: false
    default: 'false'
  sentry:
    description: 'Notify Sentry'
    required: false
    default: 'false'
  sentry-override-environment:
    description: 'Overrides environment sent to Sentry on release'
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout for Sentry Commits
      if: always() && inputs.sentry == 'true' && inputs.deploy-state == 'successful'
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Push Release Info to Sentry
      if: always() && inputs.sentry == 'true' && inputs.deploy-state == 'successful'
      uses: getsentry/action-release@v1
      with:
        ignore_empty: true
        ignore_missing: true
        finalize: ${{ (inputs.deploy-state == 'successful' ) && true || false }}
        environment: ${{ (inputs.sentry-override-environment && inputs.sentry-override-environment) || inputs.environment }}
        version: ${{ inputs.revision }}

    - name: Create New Relic deployment marker
      if: always() && inputs.new-relic == 'true' && inputs.deploy-state == 'successful'
      uses: newrelic/deployment-marker-action@v1
      with:
        apiKey: ${{ env.NEW_RELIC_API_KEY }}
        accountId: ${{ env.NEW_RELIC_ACCOUNT_ID }}
        applicationId: ${{ inputs.new-relic-application-id }}
        revision: ${{ inputs.revision }}

    - name: Post to a Slack channel
      if: always() && inputs.slack == 'true'
      uses: slackapi/slack-github-action@v1.16.0
      with:
        channel-id: 'deployments'
        payload: |
          {
            "as_user": false,
            "username": "GitHub Action",
            "attachments": [
              {
                "mrkdwn_in": [
                    "pretext",
                    "text",
                    "value"
                ],
                "pretext": "Deployment to <https://github.com/${{ github.repository }}|${{ github.repository }}>",
                "color": "${{ (inputs.deploy-state == 'successful' && '#36a64f') || '#bd2b2b' }}",
                "fields": [
                  {
                    "title": "Author",
                    "value": "<https://github.com/${{ github.actor }}|${{ github.actor }}>",
                    "short": false
                  },
                  {
                    "title": "Version",
                    "value": "<https://github.com/${{ github.repository }}/commit/${{ inputs.revision }}|${{ inputs.revision }}>",
                    "short": true
                  },
                  {
                    "title": "Environment",
                    "value": "<https://github.com/${{ github.repository }}/deployments/activity_log?environment=${{ inputs.environment }}|${{ inputs.environment }}>",
                    "short": true
                  },
                  {
                    "title": "Workflow",
                    "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} #${{ github.run_number }}>",
                    "short": true
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ env.SLACK_BOT_TOKEN }}
